### ISSUE TITLE
cannot load jars of spring-* under lib/ dir

### ISSUE THREAD

**Issue by guoqick** [Tencent/TencentKona-11#11]
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/context/support/FileSystemXmlApplicationContext
        at com.flowpp.pipe.flowai_v2.biz.main.FlowaiProcess.main(FlowaiProcess.java:22)
        at com.flowpp.pipe.flowai_v2.FlowAIProjectV2.init(FlowAIProjectV2.java:79)
        at com.flowpp.pipe.service.DataService.init(DataService.java:39)
        at com.flowpp.pipe.Main.main(Main.java:62)
Caused by: java.lang.ClassNotFoundException: org.springframework.context.support.FileSystemXmlApplicationContext
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 4 more

my start script:

#!/bin/bash
cd $(dirname $0)
filename=$(ls | grep flowpipe | grep .jar)

nohup /home/flowpp/guoqi/TencentKona-11.0.12.b1_fiber/bin/java -Xmx40g -Xms40g -Xmn20g \
-XX:+UnlockExperimentalVMOptions \
-XX:+UseZGC \
-Xlog:gc* \
-Xloggc:gc.log \
-XX:-DontCompileHugeMethods \
-XX:+HeapDumpOnOutOfMemoryError \
-XX:ErrorFile=pipe_error_%p.log \
--add-modules java.sql,java.xml -classpath ./*jar:./lib/*:./plugins/*:./lib/plug/*:./lib/plug/lib/* -Djava.library.path=./native -jar ${filename} > screen.log 2>&1 &

**Comment by shiyuexw** [comment]
can you please provide the example for the issue?

**Comment by shiyuexw** [comment]
the jar under lib/ ? if yes, please use lib/* in classpath.

**Comment by guoqick** [comment]
lib/*  can‘t make use，I resolved this problem by  package all jars in MANIFEST.MF
